# Generated by Django 4.0.5 on 2022-06-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='id пользователя')),
                ('username', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('device_model', models.CharField(max_length=150, verbose_name='Модель девайса')),
                ('client_version', models.CharField(max_length=100, verbose_name='Версия клиента')),
                ('periodicity', models.TextField(verbose_name='Частота')),
                ('type_of_problem', models.CharField(max_length=50, verbose_name='Тип проблемы')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Баг репорт',
                'verbose_name_plural': 'Баг репорты',
                'db_table': 'bug_report',
            },
        ),
    ]
