# Generated by Django 4.0.5 on 2022-06-17 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_bug_testing', '0002_userphone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugreport',
            name='client_version',
        ),
        migrations.RemoveField(
            model_name='bugreport',
            name='file',
        ),
        migrations.AddField(
            model_name='bugreport',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='FileReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_report', to='app_bug_testing.bugreport', verbose_name='Репорт')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'db_table': 'file_report',
            },
        ),
    ]
