# Generated by Django 4.0.5 on 2022-06-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_zbt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(max_length=40, null=True, verbose_name='Электронная почта'),
        ),
    ]
