# Generated by Django 4.0.5 on 2022-06-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_zbt', '0002_userprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=20, verbose_name='Команда')),
                ('status', models.CharField(choices=[('Закрыта', 'Закрыта'), ('Открыта', 'Открыта')], default='Закрыта', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Активация команды',
                'verbose_name_plural': 'Активация команд',
            },
        ),
    ]
