# Generated by Django 4.0.5 on 2022-06-22 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_zbt', '0003_commandactivity'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commandactivity',
            table='zbt_command',
        ),
    ]
