# Generated by Django 4.0.5 on 2022-06-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_zbt', '0004_alter_commandactivity_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=20, verbose_name='ip-адрес')),
            ],
            options={
                'verbose_name': 'IP адрес',
                'verbose_name_plural': 'IP адреса',
                'db_table': 'zbt_ip_address',
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('Активный', 'Активный'), ('Заблокирован', 'Заблокирован')], default='Новый', max_length=20, verbose_name='Статус'),
        ),
    ]
